name: unmarshal
description: A Future-based wrapper around the Unmarshal APIs, providing comprehensive data on wallets, tokens, prices and protocols across 16+ blockchains for your decentralized applications.
version: 1.0.0
repository: https://github.com/0xdir/unmarshal_dart

environment:
  sdk: ^3.0.0

dependencies:
   http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0